### ISSUE TITLE
[bug] Implement Multi-Stage Build in Dockerfile

### ISSUE THREAD

**Issue by Saurav-Pant** [WeMakeDevs/wemakedevs#814] opened 2023-10-18 13:46 UTC
### Describe the bug

The current Dockerfile lacks a multi-stage build. Adding this enhancement significantly reduces the image size, optimizes distribution, and simplifies container management.

### To Reproduce

Go to Dockerfile 
and add this 
`COPY package*.json ./ `     before this line `COPY . .`

**Comment by Koushik1311** [comment] 2023-10-20 16:33
I would like to work on this issue

**Comment by SaptarshiSarkar12** [comment] 2023-11-11 08:59
@AnuragThePathak Can I work on this issue?

**Comment by AnuragThePathak** [comment] 2023-11-11 18:41
@SaptarshiSarkar12 go ahead

**Comment by SaptarshiSarkar12** [comment] 2023-11-12 01:55
@AnuragThePathak Thank you for assigning this issue to me 😁

**Comment by AnuragThePathak** [comment] 2023-11-18 09:47
@SaptarshiSarkar12 you should use package*.json then only package-lock.json will be copied

**Comment by SaptarshiSarkar12** [comment] 2023-11-18 09:51
@AnuragThePathak I was using `npm install` previously. So, if I use `package-lock.json`, then, I also need to change the command to `npm ci`, right?

**Comment by AnuragThePathak** [comment] 2023-11-18 13:00
Yes you must use `npm ci` else we may see unintended behaviors in production.

**Comment by SaptarshiSarkar12** [comment] 2023-11-18 13:02
@AnuragThePathak Okay. I have added. Please check #827

**Closed** 2023-11-19 18:36 UTC
Labels: bug
