### ISSUE TITLE
[feat] Header component for dedicated WMD opensource page

### ISSUE THREAD

**Issue by hrutik7** [WeMakeDevs/wemakedevs#553] opened 2023-04-12 07:36 UTC
### Would you like to have a new feature? Please describe.

As discussed in issue #549 there we have to develop a new page with the following components 

- Header
- About
- Why open source?
- How to get involved
- Our projects
- Testimonials
- Join us
- FAQ
- Partner
- Footer

**Comment by AnuragThePathak** [comment] 2023-04-14 09:53
Duplicate of #549

**Closed by AnuragThePathak** 2023-04-14 09:53 UTC
Labels: enhancement
