### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by Spyder15** [WeMakeDevs/wemakedevs#169] opened 2022-12-04 22:56 UTC
### Describe the bug

The website is still not responsive for some devices.

### To Reproduce

Use the viewing option of iphone XR, Galaxy S20 ultra or in any mobile device etc.. in inspect elements.

### Expected Behavior

no responsive

### Screenshot/ Video

<img width="286" alt="image" src="https://user-images.githubusercontent.com/97145602/205520516-3a894b63-673e-4653-b263-a613a7e2210f.png">

### Additional context

no responsive, in partner page page..

**Comment by Spyder15** [comment] 2022-12-04 22:57
Responsiveness issue on mobile view

**Comment by AnuragThePathak** [comment] 2022-12-05 06:41
Duplicate of #166

**Closed by AnuragThePathak** 2022-12-05 06:41 UTC
Labels: bug
