### ISSUE TITLE
Few features I would love to add.

### ISSUE THREAD

**Issue by tiwxri** [WeMakeDevs/wemakedevs#202] opened 2022-12-21 10:15 UTC
### What would you like to share?

1:- Education, Events and Mentorship tab is taking too much space vertically and not utilizing the space left, rather than keeping it narrow we can pt for the wider boxes. It will help the website to grab more eyes.

2:- Mentorship header is not readable due to it's size and require user to zoomout for readablitiy.

**Comment by hiteshvijayhv** [comment] 2022-12-22 13:24
Can I work on this? I understand the first one but I can't reproduce the second.

**Comment by AnuragThePathak** [comment] 2023-01-01 07:40
@tiwxri ig these issues are fixed in the latest version?

**Closed** 2023-01-01 08:02 UTC
Labels: contributor
