### ISSUE TITLE
[bug] Newsletter form submits without clicking "I Agree" checkbox

### ISSUE THREAD

**Issue by harshvarddhantiwari** [WeMakeDevs/wemakedevs#742] opened 2023-08-19 07:51 UTC
### Describe the bug

The newsletter form gets submitted even if the "I Agree" checkbox is not clicked. This issue persists on all types of devices, whether someone clicks the checkbox or not. 

### Expected Behavior

It should warn users if they have not accepted the terms and conditions of the newsletter. 

### Screenshot/ Video

![Screenshot 2023-08-19 125504](https://github.com/WeMakeDevs/wemakedevs/assets/24490735/bf1ee4a7-7180-44c1-88d4-ce48766e48c9)

![Screenshot 2023-08-19 125515](https://github.com/WeMakeDevs/wemakedevs/assets/24490735/306a0465-2d9e-49ea-b01e-6b6eb9288539)

**Comment by AnuragThePathak** [comment] 2023-08-21 14:32
@Chandraprakash-Darji is this something to do on our end or hash node?

**Comment by diva-21** [comment] 2023-08-21 18:11
Hey @AnuragThePathak , can i take up this task to solve the bug reported?
I am very much intrested to this , please assign if its possible....

**Comment by AnuragThePathak** [comment] 2023-08-22 09:46
@diva-21 did you notice what I mentioned before your comment?

Or do you already have the idea how to fix it? If yes then we don't need to wait for @Chandraprakash-Darji's confirmation.

**Comment by Roshan4518Git** [comment] 2023-08-22 11:08
Hello, @harshvarddhantiwari. I'm having trouble locating that particular line of code for the checkbox. Could you please let me know the file in which this section is located?

**Comment by diva-21** [comment] 2023-08-22 18:53
> @diva-21 did you notice what I mentioned before your comment?
> 
> Or do you already have the idea how to fix it? If yes then we don't need to wait for @Chandraprakash-Darji's confirmation.

sure will look into it and if its not solved yet, i will take up

**Comment by AnuragThePathak** [comment] 2023-08-23 07:09
I didn't say that it's solved already, rather said it's not part of the website instead directly used from hash node as an iframe.

**Comment by diva-21** [comment] 2023-08-23 11:48
> I didn't say that it's solved already, rather said it's not part of the website instead directly used from hash node as an iframe.

noted

**Comment by diva-21** [comment] 2023-08-24 09:12
> I didn't say that it's solved already, rather said it's not part of the website instead directly used from hash node as an iframe.

I tested it , no issues for this . Also checked in mutliple mobile views too, its fine and working properly.

**Comment by AnuragThePathak** [comment] 2023-08-25 10:25
> > I didn't say that it's solved already, rather said it's not part of the website instead directly used from hash node as an iframe.
> 
> I tested it , no issues for this . Also checked in mutliple mobile views too, its fine and working properly.


@diva-21 As per I can see the issue is real, what did you mean by "no issues for this" though?

**Comment by diva-21** [comment] 2023-08-25 11:51
> > > I didn't say that it's solved already, rather said it's not part of the website instead directly used from hash node as an iframe.
> > 
> > 
> > I tested it , no issues for this . Also checked in mutliple mobile views too, its fine and working properly.
> 
> @diva-21 As per I can see the issue is real, what did you mean by "no issues for this" though?

oh sorry now i got it, my bad :'[ . Looking into it

**Comment by Chandraprakash-Darji** [comment] 2023-08-27 07:46
@AnuragThePathak Sorry for the late reply.

This is a form provided by the newsletter service provider. Mothing to do with us. 

We can close this issue.

**Comment by AnuragThePathak** [comment] 2023-08-28 15:20
@Chandraprakash-Darji thanks for the confirmation.

**Closed by AnuragThePathak** 2023-08-28 15:20 UTC
Labels: bug
