### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by Jayaditya-Contributor** [WeMakeDevs/wemakedevs#168] opened 2022-12-04 19:02 UTC
### Describe the bug

Hey the partner with us section is not mobile friendly , it would be great

if the work is done that

### To Reproduce

![Screenshot_20221205_003051](https://user-images.githubusercontent.com/107139663/205510031-5c5783c1-3919-4f63-8d4f-6b0e5b61cc35.png)

### Expected Behavior

making them readable not jumbled up

**Comment by Jayaditya-Contributor** [comment] 2022-12-04 19:02
I would like to work on this issue

**Comment by AnuragThePathak** [comment] 2022-12-05 06:41
Duplicate of #166

**Closed by AnuragThePathak** 2022-12-05 06:41 UTC
Labels: bug
