### ISSUE TITLE
Auto carousel for testimonials for mobile view

### ISSUE THREAD

**Issue by hparashar27** [WeMakeDevs/wemakedevs#308] opened 2023-01-06 17:17 UTC
### Would you like to have a new feature? Please describe.

I think , it will be more better if there is auto carousel for testimonials  in mobile view ,

https://user-images.githubusercontent.com/96375055/211063086-01370822-4af2-4fa2-8e83-47b3bc12ec3c.mp4

### How would this feature be beneficial for the project

* it can show testimonial for more no. of people
*  Occupies less space on landing page
*  gives better user experience

**Comment by joeshajan** [comment] 2023-01-08 05:23
Good idea @hparashar27. If maintainers feel this feature needs to be implemented assign this to me I would like to do this.

**Comment by AnuragThePathak** [comment] 2023-01-17 11:51
duplicate of #333

**Closed by AnuragThePathak** 2023-01-17 11:51 UTC
Labels: enhancement
