### ISSUE TITLE
[bug] inconsistenet on-hover effects

### ISSUE THREAD

**Issue by divyanshchahar** [WeMakeDevs/wemakedevs#222] opened 2022-12-23 08:35 UTC
### Describe the bug

Cursor changes to an upward-right facing arrow when hovering over the  following links
- events button in the footer
- links to socials at the bottom of the page  (refer to screenshot)

Except for the links mentioned above, the cursor changes to a pointer when hovering over links. This inconsistent effect is bad for UX. It should be consistent across the entire website

### To Reproduce

Just visit the website from a desktop computer.

### Expected Behavior

When hovering on links cursor should change to a pointer

### Screenshot/ Video

![bug](https://user-images.githubusercontent.com/40364504/209301941-fc2a320d-084a-486c-95bc-11f0bb3992ba.png)

**Comment by Chandraprakash-Darji** [comment] 2022-12-23 08:53
@divyanshchahar Arrow means when you click on the link it will open in a new tab.
It is a feature not a bug

**Comment by divyanshchahar** [comment] 2022-12-23 10:04
> @divyanshchahar Arrow means when you click on the link it will open in a new tab. It is a feature not a bug

If it is a feature, then it is not applied consistently across all links. All the links ( except the ones which trigger scrolling ) open in a new tab, but this feature is only applied to the links I mentioned.

**Comment by Chandraprakash-Darji** [comment] 2022-12-23 10:16
@divyanshchahar I am working on updating every link it will fixed by today

**Closed** 2022-12-24 16:17 UTC
Labels: bug
